### ISSUE TITLE
Can't rename existing Nav links

### ISSUE THREAD

**Issue by juliencharette** [engram-design/CPNav#23]
Trying to rename existing navigation links. This is what I got from the chrome console:

```
CDbException

CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'newWindow' cannot be null. The SQL statement executed was: UPDATE `cpnav_navs` SET `enabled`=:yp0, `order`=:yp1, `manualNav`=:yp2, `newWindow`=:yp3, `id`=:yp4, `layoutId`=:yp5, `handle`=:yp6, `prevLabel`=:yp7, `currLabel`=:yp8, `prevUrl`=:yp9, `url`=:yp10, `icon`=:yp11, `customIcon`=:yp12, `dateCreated`=:yp13, `dateUpdated`=:yp14, `uid`=:yp15 WHERE `cpnav_navs`.`id`=6. Bound with :yp0=1, :yp1=5, :yp2=0, :yp3=NULL, :yp4=6, :yp5=1, :yp6='seomatic', :yp7='SEOmatic', :yp8='SEO', :yp9='seomatic', :yp10='seomatic', :yp11='iconSvg-seomatic', :yp12='', :yp13='2016-09-27 12:26:00', :yp14='2016-09-27 12:33:53', :yp15='200848b4-5e61-4054-b047-f8ac8f6f01b0' (/vagrant/craft/app/framework/db/CDbCommand.php:358)

#0 /vagrant/craft/app/framework/db/ar/CActiveRecord.php(1754): CDbCommand->execute()
#1 /vagrant/craft/app/framework/db/ar/CActiveRecord.php(1128): CActiveRecord->updateByPk('6', Array)
#2 /vagrant/craft/app/framework/db/ar/CActiveRecord.php(810): CActiveRecord->update(NULL)
#3 /vagrant/craft/plugins/cpnav/services/CpNav_NavService.php(64): CActiveRecord->save(false)
#4 /vagrant/craft/plugins/cpnav/controllers/CpNav_NavController.php(117): Craft\CpNav_NavService->save(Object(Craft\CpNav_NavModel))
#5 /vagrant/craft/app/framework/web/actions/CInlineAction.php(49): Craft\CpNav_NavController->actionSave()
#6 /vagrant/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /vagrant/craft/app/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /vagrant/craft/app/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /vagrant/craft/app/framework/web/CWebApplication.php(282): CController->run('save')
#10 /vagrant/craft/app/etc/web/WebApp.php(818): CWebApplication->runController('cpNav/nav/save')
#11 /vagrant/craft/app/etc/web/WebApp.php(288): Craft\WebApp->_processActionRequest()
#12 /vagrant/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#13 /vagrant/craft/app/index.php(62): CApplication->run()
#14 /vagrant/public/index.php(32): require_once('/vagrant/craft/...')
#15 {main}
```

**Comment by engram-design** [comment]
Struggling to replicate this with all manner of testing. Can you confirm if you're trying to rename a build-in nav item (Entries, Dashboard, etc), a plugin, or a manually-created nav item?

**Comment by engram-design** [comment]
Actually - if you're able to give the latest master a go, that may help!

**Comment by juliencharette** [comment]
I'm trying to do both (rename built-in and custom items) and get the same error. I will try the latest master and let you know.

**Comment by engram-design** [comment]
Any further progress on this? Can't seem to reproduce no matter how I try. Thinking it might be even worth getting in touch on Slack and grabbing your `cpnav_navs` table.

**Comment by juliencharette** [comment]
Updated Craft to latest 2.6.2950 (Oct 31) and everything is working as it should.

**Comment by engram-design** [comment]
Closing for now due to a Craft update fixing. Please reopen if you have issues.
