### ISSUE TITLE
'Setting unknown property' on fresh install

### ISSUE THREAD

**Issue by ThijmenDeValk** [engram-design/CPNav#65]
### Description
I'm getting an error on a new fresh install of both the plug-in and Craft. As soon as I go to the plug-in settings page, I get an error 500 `Setting unknown property: verbb\cpnav\events\NavigationEvent::navigation`.

### Steps to reproduce

1. Install v3.0.1 on a fresh Craft v3.4.3 installation
2. Go to "Control Panel Nav" in Settings
3. Error 500

### Additional info

- Plugin version: 3.0.1
- Craft version: 3.4.3

### Stacktrace
```
yii\base\UnknownPropertyException: Setting unknown property: verbb\cpnav\events\NavigationEvent::navigation in /project/vendor/yiisoft/yii2/base/BaseObject.php:163
Stack trace:
#0 /project/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\BaseObject->__set('navigation', Object(verbb\cpnav\models\Navigation))
#1 /project/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(verbb\cpnav\events\NavigationEvent), Array)
#2 /project/vendor/verbb/cp-nav/src/services/NavigationsService.php(118): yii\base\BaseObject->__construct(Array)
#3 /project/vendor/verbb/cp-nav/src/services/Service.php(166): verbb\cpnav\services\NavigationsService->saveNavigation(Object(verbb\cpnav\models\Navigation))
#4 /project/vendor/verbb/cp-nav/src/controllers/NavigationController.php(32): verbb\cpnav\services\Service->populateOriginalNavigationItems(1)
#5 /project/vendor/yiisoft/yii2/base/Controller.php(155): verbb\cpnav\controllers\NavigationController->beforeAction(Object(yii\base\InlineAction))
#6 /project/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('index', Array)
#7 /project/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('index', Array)
#8 /project/vendor/craftcms/cms/src/web/Application.php(290): yii\base\Module->runAction('cp-nav/navigati...', Array)
#9 /project/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('cp-nav/navigati...', Array)
#10 /project/vendor/craftcms/cms/src/web/Application.php(275): yii\web\Application->handleRequest(Object(craft\web\Request))
#11 /project/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#12 /project/web/index.php(21): yii\base\Application->run()
#13 {main}
```

**Comment by engram-design** [comment]
Fixed in [3.0.2](https://github.com/verbb/cp-nav/releases/tag/3.0.2)
