### ISSUE TITLE
Migration failure

### ISSUE THREAD

**Issue by darylknight** [engram-design/CPNav#80]
**Description**
I just tried updating Control Panel Nav from 3.0.12 to 3.0.13 on Craft 3.4.30 and got this:

```
One of Control Panel Nav’s migrations failed.

yii\base\ErrorException: Invalid argument supplied for foreach()

Migration: verbb\cpnav\migrations\m200812_000000_fix_layoutid

Output:

Exception: Invalid argument supplied for foreach() (/Users/dknight/Sites/mynb/vendor/verbb/cp-nav/src/migrations/m200812_000000_fix_layoutid.php:34)
#0 /Users/dknight/Sites/mynb/vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError(2, 'Invalid argumen...', '/Users/darylkni...', 34)
#1 /Users/dknight/Sites/mynb/vendor/verbb/cp-nav/src/migrations/m200812_000000_fix_layoutid.php(34): craft\web\ErrorHandler->handleError(2, 'Invalid argumen...', '/Users/darylkni...', 34, Array)
#2 /Users/dknight/Sites/mynb/vendor/craftcms/cms/src/db/Migration.php(52): verbb\cpnav\migrations\m200812_000000_fix_layoutid->safeUp()
#3 /Users/dknight/Sites/mynb/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#4 /Users/dknight/Sites/mynb/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(verbb\cpnav\migrations\m200812_000000_fix_layoutid))
#5 /Users/dknight/Sites/mynb/vendor/craftcms/cms/src/services/Updates.php(233): craft\db\MigrationManager->up()
#6 /Users/dknight/Sites/mynb/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations(Array)
#7 /Users/dknight/Sites/mynb/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#8 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#9 /Users/dknight/Sites/mynb/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /Users/dknight/Sites/mynb/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /Users/dknight/Sites/mynb/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('migrate', Array)
#12 /Users/dknight/Sites/mynb/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#13 /Users/dknight/Sites/mynb/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('updater/migrate', Array)
#14 /Users/dknight/Sites/mynb/vendor/craftcms/cms/src/web/Application.php(646): craft\web\Application->runAction('updater/migrate')
#15 /Users/dknight/Sites/mynb/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#16 /Users/dknight/Sites/mynb/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /Users/dknight/Sites/mynb/public/index.php(21): yii\base\Application->run()
#18 /Users/dknight/.composer/vendor/laravel/valet/server.php(158): require('/Users/darylkni...')
#19 {main}
```

**Additional info**
- Plugin version: 3.0.13
- Craft version: 3.4.30
- Multi-site: No
- PHP 7.4.8

**Comment by engram-design** [comment]
Should be fixed in [3.0.13.1](https://github.com/verbb/cp-nav/releases/tag/3.0.13.1)
